From pearsonsm at ornl.gov  Fri Jul  5 08:51:09 2024
From: pearsonsm at ornl.gov (Pearson, Scott)
Date: Fri, 5 Jul 2024 15:51:09 +0000
Subject: [pdal] reader.ept error - Could read from
Message-ID: <SA9PR09MB588618C125C990BDE333A7DFDFDF2@SA9PR09MB5886.namprd09.prod.outlook.com>

Dear PDA folks,

I have an error using readers.ept in a PDAL pipeline.  Using instructions on the Quickstart page<https://pdal.io/en/2.7.2/quickstart.html>, PDAL (v. 2.7.2) is installed using miniconda (conda v. 24.5.0) and applied updates were applied to conda and pdal installations.  The "pdal info autzen.laz -p 0" command works, so I've assume that the PDAL install was successful.

When I run "pdal pipeline Plot_176612216020004.json -debug", I receive this output and error:
"(PDAL Debug) Debugging...
(pdal pipeline readers.ept Debug) PDAL: readers.ept: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json "

The contents of Plot_176612216020004.json are:
[
  {
    "tag": "ept_reader",
    "type": "readers.ept",
    "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
    "filename": https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json,
    "resolution": "0.01",
    "threads": "4"
  },
  {
    "tag": "las_writer",
    "type": "writers.las",
    "filename": "USGS_LPC_TN_27County_blk4_2015_LAS_2018_176612216020004.laz",
    "compression": "laszip",
    "extra_dims": "all",
    "forward": "header, vlr",
    "offset_x": "auto",
    "offset_y": "auto",
    "offset_z": "auto",
    "scale_x": "0.01",
    "scale_y": "0.01",
    "scale_z": "0.01"
  }
]

I can access the etp.json file listed under filename using my browser and also using a curl command from the conda prompt.
I have also tried the Iowa example from this tutorial and receive the same "Could not read from ...." error.

Any suggestions for solving this problem?  My overall goal is to download lidar point clouds for a set of 200 field plots (3 ha each).

Thank you,
Scott
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240705/587a58b9/attachment.htm>

From runette at gmail.com  Sat Jul  6 02:09:45 2024
From: runette at gmail.com (Paul Harwood)
Date: Sat, 6 Jul 2024 10:09:45 +0100
Subject: [pdal] reader.ept error - Could read from
In-Reply-To: <SA9PR09MB588618C125C990BDE333A7DFDFDF2@SA9PR09MB5886.namprd09.prod.outlook.com>
References: <SA9PR09MB588618C125C990BDE333A7DFDFDF2@SA9PR09MB5886.namprd09.prod.outlook.com>
Message-ID: <CAE8nN5P2OQgPPH7J1_JBZ_6fiqmuBpQHQotG=DaSJXG-o-LGvw@mail.gmail.com>

I don't know if this is just an artefact of the email - but :

https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json

should be:

"
https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json
"

On Fri, 5 Jul 2024 at 17:24, Pearson, Scott via pdal <pdal at lists.osgeo.org>
wrote:

> Dear PDA folks,
>
>
>
> I have an error using readers.ept in a PDAL pipeline.  Using instructions
> on the Quickstart page <https://pdal.io/en/2.7.2/quickstart.html>, PDAL
> (v. 2.7.2) is installed using miniconda (conda v. 24.5.0) and applied
> updates were applied to conda and pdal installations.  The ?pdal info
> autzen.laz -p 0? command works, so I?ve assume that the PDAL install was
> successful.
>
>
>
> When I run ?pdal pipeline Plot_176612216020004.json ?debug?, I receive
> this output and error:
>
> ?(PDAL Debug) Debugging...
>
> (pdal pipeline readers.ept Debug) PDAL: readers.ept: Could not read from
> s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json
> ?
>
>
>
> The contents of Plot_176612216020004.json are:
>
> [
>
>   {
>
>     "tag": "ept_reader",
>
>     "type": "readers.ept",
>
>     "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[
> 4175665.92739632 , 4177131.3660114 ])",
>
>     "filename":
> https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json
> ,
>
>     "resolution": "0.01",
>
>     "threads": "4"
>
>   },
>
>   {
>
>     "tag": "las_writer",
>
>     "type": "writers.las",
>
>     "filename":
> "USGS_LPC_TN_27County_blk4_2015_LAS_2018_176612216020004.laz",
>
>     "compression": "laszip",
>
>     "extra_dims": "all",
>
>     "forward": "header, vlr",
>
>     "offset_x": "auto",
>
>     "offset_y": "auto",
>
>     "offset_z": "auto",
>
>     "scale_x": "0.01",
>
>     "scale_y": "0.01",
>
>     "scale_z": "0.01"
>
>   }
>
> ]
>
>
>
> I can access the etp.json file listed under filename using my browser and
> also using a curl command from the conda prompt.
>
> I have also tried the Iowa example from this tutorial and receive the same
> ?Could not read from ?.? error.
>
>
>
> Any suggestions for solving this problem?  My overall goal is to download
> lidar point clouds for a set of 200 field plots (3 ha each).
>
>
>
> Thank you,
>
> Scott
> _______________________________________________
> pdal mailing list
> pdal at lists.osgeo.org
> https://lists.osgeo.org/mailman/listinfo/pdal
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240706/63479959/attachment.htm>

From pearsonsm at ornl.gov  Mon Jul  8 03:57:21 2024
From: pearsonsm at ornl.gov (Pearson, Scott)
Date: Mon, 8 Jul 2024 10:57:21 +0000
Subject: [pdal] [EXTERNAL] Re:  reader.ept error - Could read from
In-Reply-To: <CAE8nN5P2OQgPPH7J1_JBZ_6fiqmuBpQHQotG=DaSJXG-o-LGvw@mail.gmail.com>
References: <SA9PR09MB588618C125C990BDE333A7DFDFDF2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <CAE8nN5P2OQgPPH7J1_JBZ_6fiqmuBpQHQotG=DaSJXG-o-LGvw@mail.gmail.com>
Message-ID: <SA9PR09MB588667EE922EC5CAE3EA4DB7DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>

Hi Paul,

The URL is quoted in my input JSON file.  In the email message, Microsoft Outlook converted the URL text to a link and dropped the quotes.  Here's a snippet from the JSON with quotation marks preserved:
{
    "tag": "ept_reader",
    "type": "readers.ept",
    "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
    "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json",
    "resolution": "0.01",
    "threads": "4"
  }

Thanks,
Scott


From: Paul Harwood <runette at gmail.com>
Sent: Saturday, July 6, 2024 5:10 AM
To: Pearson, Scott <pearsonsm at ornl.gov>
Cc: pdal at lists.osgeo.org
Subject: [EXTERNAL] Re: [pdal] reader.ept error - Could read from

I don't know if this is just an artefact of the email - but :

https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>

should be:

"https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>"

On Fri, 5 Jul 2024 at 17:24, Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:
Dear PDAL folks,
 I have an error using readers.ept in a PDAL pipeline.  Using instructions on the Quickstart page<https://urldefense.us/v2/url?u=https-3A__pdal.io_en_2.7.2_quickstart.html&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=su9lNnhWcUnIS-p1ASVmGNvlVbDN_kimfMgeqAjZdLE&e=>, PDAL (v. 2.7.2) is installed using miniconda (conda v. 24.5.0) and applied updates were applied to conda and pdal installations.  The "pdal info autzen.laz -p 0" command works, so I've assume that the PDAL install was successful.
 When I run "pdal pipeline Plot_176612216020004.json -debug", I receive this output and error:
"(PDAL Debug) Debugging...
(pdal pipeline readers.ept Debug) PDAL: readers.ept: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=http-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=grZ4fqpuKLbRQaHxZRQsSUZEWar0gYK3B0ovPUvWjCc&e=> "
 The contents of Plot_176612216020004.json are:
[
  {
    "tag": "ept_reader",
    "type": "readers.ept",
    "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
    "filename": "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json",
    "resolution": "0.01",
    "threads": "4"
  },
  {
    "tag": "las_writer",
    "type": "writers.las",
    "filename": "USGS_LPC_TN_27County_blk4_2015_LAS_2018_176612216020004.laz",
    "compression": "laszip",
    "extra_dims": "all",
    "forward": "header, vlr",
    "offset_x": "auto",
    "offset_y": "auto",
    "offset_z": "auto",
    "scale_x": "0.01",
    "scale_y": "0.01",
    "scale_z": "0.01"
  }
]

I can access the etp.json file listed under filename using my browser and also using a curl command from the conda prompt.
I have also tried the Iowa example from this tutorial and receive the same "Could not read from ...." error.
 Any suggestions for solving this problem?  My overall goal is to download lidar point clouds for a set of 200 field plots (3 ha each).
 Thank you,
Scott
_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=PST3C28-L5iw9E-wtUJA0LshiHNBg78HGTpOn1OH4aU&e=>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240708/48b88395/attachment-0001.htm>

From kirk.waters at noaa.gov  Mon Jul  8 04:34:36 2024
From: kirk.waters at noaa.gov (Kirk Waters - NOAA Federal)
Date: Mon, 8 Jul 2024 07:34:36 -0400
Subject: [pdal] [EXTERNAL] Re: reader.ept error - Could read from
In-Reply-To: <SA9PR09MB588667EE922EC5CAE3EA4DB7DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
References: <SA9PR09MB588618C125C990BDE333A7DFDFDF2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <CAE8nN5P2OQgPPH7J1_JBZ_6fiqmuBpQHQotG=DaSJXG-o-LGvw@mail.gmail.com>
 <SA9PR09MB588667EE922EC5CAE3EA4DB7DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
Message-ID: <CADm=QrQv8H-6xYb0Qo0pAZKF1=ebu-rOzV1qE020o-UYmKUejA@mail.gmail.com>

I've seen this error message before with other files. When I pulled the
ept.json file to verify, it looked fine. Rerunning the command also worked
fine. This has made me believe it's been a network issue. For my automated
processes, I now try to catch that response, sleep a minute, and then try
again. Has it been consistently failing?

Kirk Waters, PhD
NOAA Office for Coastal Management
Applied Sciences Program
coast.noaa.gov/digitalcoast




On Mon, Jul 8, 2024 at 7:26?AM Pearson, Scott via pdal <pdal at lists.osgeo.org>
wrote:

> Hi Paul,
>
>
>
> The URL is quoted in my input JSON file.  In the email message, Microsoft
> Outlook converted the URL text to a link and dropped the quotes.  Here?s a
> snippet from the JSON with quotation marks preserved:
>
> {
>
>     "tag": "ept_reader",
>
>     "type": "readers.ept",
>
>     "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[
> 4175665.92739632 , 4177131.3660114 ])",
>
>     "filename": ?
> https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json
> ?,
>
>     "resolution": "0.01",
>
>     "threads": "4"
>
>   }
>
>
>
> Thanks,
>
> Scott
>
>
>
>
>
> *From:* Paul Harwood <runette at gmail.com>
> *Sent:* Saturday, July 6, 2024 5:10 AM
> *To:* Pearson, Scott <pearsonsm at ornl.gov>
> *Cc:* pdal at lists.osgeo.org
> *Subject:* [EXTERNAL] Re: [pdal] reader.ept error - Could read from
>
>
>
> I don't know if this is just an artefact of the email - but :
>
>
>
>
> https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json
> <https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>
>
>
>
> should be:
>
>
> "
> https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json
> <https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>
> "
>
>
>
> On Fri, 5 Jul 2024 at 17:24, Pearson, Scott via pdal <pdal at lists.osgeo.org>
> wrote:
>
> Dear PDAL folks,
>
>  I have an error using readers.ept in a PDAL pipeline.  Using instructions
> on the Quickstart page
> <https://urldefense.us/v2/url?u=https-3A__pdal.io_en_2.7.2_quickstart.html&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=su9lNnhWcUnIS-p1ASVmGNvlVbDN_kimfMgeqAjZdLE&e=>,
> PDAL (v. 2.7.2) is installed using miniconda (conda v. 24.5.0) and applied
> updates were applied to conda and pdal installations.  The ?pdal info
> autzen.laz -p 0? command works, so I?ve assume that the PDAL install was
> successful.
>
>  When I run ?pdal pipeline Plot_176612216020004.json ?debug?, I receive
> this output and error:
>
> ?(PDAL Debug) Debugging...
>
> (pdal pipeline readers.ept Debug) PDAL: readers.ept: Could not read from
> s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json
> <https://urldefense.us/v2/url?u=http-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=grZ4fqpuKLbRQaHxZRQsSUZEWar0gYK3B0ovPUvWjCc&e=>
> ?
>
>  The contents of Plot_176612216020004.json are:
>
> [
>
>   {
>
>     "tag": "ept_reader",
>
>     "type": "readers.ept",
>
>     "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[
> 4175665.92739632 , 4177131.3660114 ])",
>
>     "filename": ?
> https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json
> ?,
>
>     "resolution": "0.01",
>
>     "threads": "4"
>
>   },
>
>   {
>
>     "tag": "las_writer",
>
>     "type": "writers.las",
>
>     "filename":
> "USGS_LPC_TN_27County_blk4_2015_LAS_2018_176612216020004.laz",
>
>     "compression": "laszip",
>
>     "extra_dims": "all",
>
>     "forward": "header, vlr",
>
>     "offset_x": "auto",
>
>     "offset_y": "auto",
>
>     "offset_z": "auto",
>
>     "scale_x": "0.01",
>
>     "scale_y": "0.01",
>
>     "scale_z": "0.01"
>
>   }
>
> ]
>
>
>
> I can access the etp.json file listed under filename using my browser and
> also using a curl command from the conda prompt.
>
> I have also tried the Iowa example from this tutorial and receive the same
> ?Could not read from ?.? error.
>
>  Any suggestions for solving this problem?  My overall goal is to download
> lidar point clouds for a set of 200 field plots (3 ha each).
>
>  Thank you,
>
> Scott
>
> _______________________________________________
> pdal mailing list
> pdal at lists.osgeo.org
> https://lists.osgeo.org/mailman/listinfo/pdal
> <https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=PST3C28-L5iw9E-wtUJA0LshiHNBg78HGTpOn1OH4aU&e=>
>
> _______________________________________________
> pdal mailing list
> pdal at lists.osgeo.org
> https://lists.osgeo.org/mailman/listinfo/pdal
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240708/951c38a1/attachment.htm>

From pearsonsm at ornl.gov  Mon Jul  8 05:05:37 2024
From: pearsonsm at ornl.gov (Pearson, Scott)
Date: Mon, 8 Jul 2024 12:05:37 +0000
Subject: [pdal] [EXTERNAL] Re: reader.ept error - Could read from
In-Reply-To: <CADm=QrQv8H-6xYb0Qo0pAZKF1=ebu-rOzV1qE020o-UYmKUejA@mail.gmail.com>
References: <SA9PR09MB588618C125C990BDE333A7DFDFDF2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <CAE8nN5P2OQgPPH7J1_JBZ_6fiqmuBpQHQotG=DaSJXG-o-LGvw@mail.gmail.com>
 <SA9PR09MB588667EE922EC5CAE3EA4DB7DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <CADm=QrQv8H-6xYb0Qo0pAZKF1=ebu-rOzV1qE020o-UYmKUejA@mail.gmail.com>
Message-ID: <SA9PR09MB5886C18F1E273E45280B2B92DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>

Hi Kirk,

I have seen the problem consistently since July 1 and again this morning.  I use a PC that is on my employer?s VPN, which might be contributing to the issue.

Scott

From: Kirk Waters - NOAA Federal <kirk.waters at noaa.gov>
Sent: Monday, July 8, 2024 7:35 AM
To: Pearson, Scott <pearsonsm at ornl.gov>
Cc: Paul Harwood <runette at gmail.com>; pdal at lists.osgeo.org
Subject: Re: [pdal] [EXTERNAL] Re: reader.ept error - Could read from

I've seen this error message before with other files. When I pulled the ept.json file to verify, it looked fine. Rerunning the command also worked fine. This has made me believe it's been a network issue. For my automated processes, I now try to catch that response, sleep a minute, and then try again. Has it been consistently failing?

Kirk Waters, PhD
NOAA Office for Coastal Management
Applied Sciences Program
coast.noaa.gov/digitalcoast<https://urldefense.us/v2/url?u=http-3A__coast.noaa.gov_digitalcoast&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=py4GkxTULW8v1KQXRdcuOrApgAtGP2DNvXXiG6LFkWU&e=>




On Mon, Jul 8, 2024 at 7:26?AM Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:
Hi Paul,

The URL is quoted in my input JSON file.  In the email message, Microsoft Outlook converted the URL text to a link and dropped the quotes.  Here?s a snippet from the JSON with quotation marks preserved:
{
    "tag": "ept_reader",
    "type": "readers.ept",
    "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
    "filename": ?https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=2fzUXpUwgQYrH-rkW6_bGLG3pgVPaUTGCCioQXewQRU&e=>?,
    "resolution": "0.01",
    "threads": "4"
  }

Thanks,
Scott


From: Paul Harwood <runette at gmail.com<mailto:runette at gmail.com>>
Sent: Saturday, July 6, 2024 5:10 AM
To: Pearson, Scott <pearsonsm at ornl.gov<mailto:pearsonsm at ornl.gov>>
Cc: pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
Subject: [EXTERNAL] Re: [pdal] reader.ept error - Could read from

I don't know if this is just an artefact of the email - but :

https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>

should be:

"https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>"

On Fri, 5 Jul 2024 at 17:24, Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:
Dear PDAL folks,
 I have an error using readers.ept in a PDAL pipeline.  Using instructions on the Quickstart page<https://urldefense.us/v2/url?u=https-3A__pdal.io_en_2.7.2_quickstart.html&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=su9lNnhWcUnIS-p1ASVmGNvlVbDN_kimfMgeqAjZdLE&e=>, PDAL (v. 2.7.2) is installed using miniconda (conda v. 24.5.0) and applied updates were applied to conda and pdal installations.  The ?pdal info autzen.laz -p 0? command works, so I?ve assume that the PDAL install was successful.
 When I run ?pdal pipeline Plot_176612216020004.json ?debug?, I receive this output and error:
?(PDAL Debug) Debugging...
(pdal pipeline readers.ept Debug) PDAL: readers.ept: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=http-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=grZ4fqpuKLbRQaHxZRQsSUZEWar0gYK3B0ovPUvWjCc&e=> ?
 The contents of Plot_176612216020004.json are:
[
  {
    "tag": "ept_reader",
    "type": "readers.ept",
    "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
    "filename": ?https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=2fzUXpUwgQYrH-rkW6_bGLG3pgVPaUTGCCioQXewQRU&e=>?,
    "resolution": "0.01",
    "threads": "4"
  },
  {
    "tag": "las_writer",
    "type": "writers.las",
    "filename": "USGS_LPC_TN_27County_blk4_2015_LAS_2018_176612216020004.laz",
    "compression": "laszip",
    "extra_dims": "all",
    "forward": "header, vlr",
    "offset_x": "auto",
    "offset_y": "auto",
    "offset_z": "auto",
    "scale_x": "0.01",
    "scale_y": "0.01",
    "scale_z": "0.01"
  }
]

I can access the etp.json file listed under filename using my browser and also using a curl command from the conda prompt.
I have also tried the Iowa example from this tutorial and receive the same ?Could not read from ?.? error.
 Any suggestions for solving this problem?  My overall goal is to download lidar point clouds for a set of 200 field plots (3 ha each).
 Thank you,
Scott
_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=PST3C28-L5iw9E-wtUJA0LshiHNBg78HGTpOn1OH4aU&e=>
_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=EsfMSNspm-xBh9dAu7TmVnuGSiMpcPqQkW6N1vKcGsc&e=>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240708/4d93d8bf/attachment-0001.htm>

From howard at hobu.co  Mon Jul  8 05:25:14 2024
From: howard at hobu.co (Howard Butler)
Date: Mon, 8 Jul 2024 07:25:14 -0500
Subject: [pdal] [EXTERNAL] Re: reader.ept error - Could read from
In-Reply-To: <SA9PR09MB5886C18F1E273E45280B2B92DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
References: <SA9PR09MB588618C125C990BDE333A7DFDFDF2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <CAE8nN5P2OQgPPH7J1_JBZ_6fiqmuBpQHQotG=DaSJXG-o-LGvw@mail.gmail.com>
 <SA9PR09MB588667EE922EC5CAE3EA4DB7DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <CADm=QrQv8H-6xYb0Qo0pAZKF1=ebu-rOzV1qE020o-UYmKUejA@mail.gmail.com>
 <SA9PR09MB5886C18F1E273E45280B2B92DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
Message-ID: <39ECB519-713E-443B-9D66-33B2D74D416C@hobu.co>

set VERBOSE=1 in your environment before running your pipeline and include the --debug switch in your pdal command to see if it will emit more diagnostic for you.

> On Jul 8, 2024, at 7:05?AM, Pearson, Scott via pdal <pdal at lists.osgeo.org> wrote:
> 
> Hi Kirk,
>  
> I have seen the problem consistently since July 1 and again this morning.  I use a PC that is on my employer?s VPN, which might be contributing to the issue.
>  
> Scott
>  
> From: Kirk Waters - NOAA Federal <kirk.waters at noaa.gov>
> Sent: Monday, July 8, 2024 7:35 AM
> To: Pearson, Scott <pearsonsm at ornl.gov>
> Cc: Paul Harwood <runette at gmail.com>; pdal at lists.osgeo.org
> Subject: Re: [pdal] [EXTERNAL] Re: reader.ept error - Could read from
>  
> I've seen this error message before with other files. When I pulled the ept.json file to verify, it looked fine. Rerunning the command also worked fine. This has made me believe it's been a network issue. For my automated processes, I now try to catch that response, sleep a minute, and then try again. Has it been consistently failing?
> 
> Kirk Waters, PhD 
> NOAA Office for Coastal Management
> Applied Sciences Program      
> coast.noaa.gov/digitalcoast <https://urldefense.us/v2/url?u=http-3A__coast.noaa.gov_digitalcoast&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=py4GkxTULW8v1KQXRdcuOrApgAtGP2DNvXXiG6LFkWU&e=>
>  
>  
>  
>  
> On Mon, Jul 8, 2024 at 7:26?AM Pearson, Scott via pdal <pdal at lists.osgeo.org <mailto:pdal at lists.osgeo.org>> wrote:
> Hi Paul,
>  
> The URL is quoted in my input JSON file.  In the email message, Microsoft Outlook converted the URL text to a link and dropped the quotes.  Here?s a snippet from the JSON with quotation marks preserved:
> {
>     "tag": "ept_reader",
>     "type": "readers.ept",
>     "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
>     "filename": ?https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json <https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=2fzUXpUwgQYrH-rkW6_bGLG3pgVPaUTGCCioQXewQRU&e=>?,
>     "resolution": "0.01",
>     "threads": "4"
>   }
>  
> Thanks,
> Scott
>  
>  
> From: Paul Harwood <runette at gmail.com <mailto:runette at gmail.com>>
> Sent: Saturday, July 6, 2024 5:10 AM
> To: Pearson, Scott <pearsonsm at ornl.gov <mailto:pearsonsm at ornl.gov>>
> Cc: pdal at lists.osgeo.org <mailto:pdal at lists.osgeo.org>
> Subject: [EXTERNAL] Re: [pdal] reader.ept error - Could read from
>  
> I don't know if this is just an artefact of the email - but :
>  
> https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json <https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>
>  
> should be:
> 
> "https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json <https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>"
>  
> On Fri, 5 Jul 2024 at 17:24, Pearson, Scott via pdal <pdal at lists.osgeo.org <mailto:pdal at lists.osgeo.org>> wrote:
> Dear PDAL folks,
>  I have an error using readers.ept in a PDAL pipeline.  Using instructions on the Quickstart page <https://urldefense.us/v2/url?u=https-3A__pdal.io_en_2.7.2_quickstart.html&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=su9lNnhWcUnIS-p1ASVmGNvlVbDN_kimfMgeqAjZdLE&e=>, PDAL (v. 2.7.2) is installed using miniconda (conda v. 24.5.0) and applied updates were applied to conda and pdal installations.  The ?pdal info autzen.laz -p 0? command works, so I?ve assume that the PDAL install was successful.
>  When I run ?pdal pipeline Plot_176612216020004.json ?debug?, I receive this output and error:
> ?(PDAL Debug) Debugging...
> (pdal pipeline readers.ept Debug) PDAL: readers.ept: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json <https://urldefense.us/v2/url?u=http-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=grZ4fqpuKLbRQaHxZRQsSUZEWar0gYK3B0ovPUvWjCc&e=> ?
>  The contents of Plot_176612216020004.json are:
> [
>   {
>     "tag": "ept_reader",
>     "type": "readers.ept",
>     "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
>     "filename": ?https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json <https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=2fzUXpUwgQYrH-rkW6_bGLG3pgVPaUTGCCioQXewQRU&e=>?,
>     "resolution": "0.01",
>     "threads": "4"
>   },
>   {
>     "tag": "las_writer",
>     "type": "writers.las",
>     "filename": "USGS_LPC_TN_27County_blk4_2015_LAS_2018_176612216020004.laz",
>     "compression": "laszip",
>     "extra_dims": "all",
>     "forward": "header, vlr",
>     "offset_x": "auto",
>     "offset_y": "auto",
>     "offset_z": "auto",
>     "scale_x": "0.01",
>     "scale_y": "0.01",
>     "scale_z": "0.01"
>   }
> ]
>  
> I can access the etp.json file listed under filename using my browser and also using a curl command from the conda prompt.
> I have also tried the Iowa example from this tutorial and receive the same ?Could not read from ?.? error.
>  Any suggestions for solving this problem?  My overall goal is to download lidar point clouds for a set of 200 field plots (3 ha each).
>  Thank you,
> Scott
> _______________________________________________
> pdal mailing list
> pdal at lists.osgeo.org <mailto:pdal at lists.osgeo.org>
> https://lists.osgeo.org/mailman/listinfo/pdal <https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=PST3C28-L5iw9E-wtUJA0LshiHNBg78HGTpOn1OH4aU&e=>
> _______________________________________________
> pdal mailing list
> pdal at lists.osgeo.org <mailto:pdal at lists.osgeo.org>
> https://lists.osgeo.org/mailman/listinfo/pdal <https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=EsfMSNspm-xBh9dAu7TmVnuGSiMpcPqQkW6N1vKcGsc&e=>_______________________________________________
> pdal mailing list
> pdal at lists.osgeo.org
> https://lists.osgeo.org/mailman/listinfo/pdal

-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240708/b55a8651/attachment-0001.htm>

From pearsonsm at ornl.gov  Mon Jul  8 05:35:44 2024
From: pearsonsm at ornl.gov (Pearson, Scott)
Date: Mon, 8 Jul 2024 12:35:44 +0000
Subject: [pdal] [EXTERNAL] Re: reader.ept error - Could read from
In-Reply-To: <39ECB519-713E-443B-9D66-33B2D74D416C@hobu.co>
References: <SA9PR09MB588618C125C990BDE333A7DFDFDF2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <CAE8nN5P2OQgPPH7J1_JBZ_6fiqmuBpQHQotG=DaSJXG-o-LGvw@mail.gmail.com>
 <SA9PR09MB588667EE922EC5CAE3EA4DB7DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <CADm=QrQv8H-6xYb0Qo0pAZKF1=ebu-rOzV1qE020o-UYmKUejA@mail.gmail.com>
 <SA9PR09MB5886C18F1E273E45280B2B92DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <39ECB519-713E-443B-9D66-33B2D74D416C@hobu.co>
Message-ID: <SA9PR09MB5886EEAD2E369D9DDD499C33DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>

Hi Howard,
Here?s what I see after setting  VERBOSE=1 :

pdal pipeline Plot_176612216020004.json --debug
(PDAL Debug) Debugging...
(pdal pipeline readers.ept Debug) Curl config:
        timeout: 5s
        followRedirect: true
        verifyPeer: true
        caBundle: (default)
        caInfo: (default)
        Proxy: (default)
* Host s3-us-west-2.amazonaws.com:443 was resolved.
* IPv6: (none)
* IPv4: 52.92.147.120, 52.92.128.104, 52.218.236.96, 52.92.152.216, 52.218.183.0, 52.218.237.32, 52.92.180.72, 52.92.138.0
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
PDAL: readers.ept: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json

Thanks,
Scott



From: Howard Butler <howard at hobu.co>
Sent: Monday, July 8, 2024 8:25 AM
To: Pearson, Scott <pearsonsm at ornl.gov>
Cc: Kirk Waters - NOAA Federal <kirk.waters at noaa.gov>; pdal at lists.osgeo.org
Subject: Re: [pdal] [EXTERNAL] Re: reader.ept error - Could read from

set VERBOSE=1 in your environment before running your pipeline and include the --debug switch in your pdal command to see if it will emit more diagnostic for you.


On Jul 8, 2024, at 7:05?AM, Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:

Hi Kirk,

I have seen the problem consistently since July 1 and again this morning.  I use a PC that is on my employer?s VPN, which might be contributing to the issue.

Scott

From: Kirk Waters - NOAA Federal <kirk.waters at noaa.gov<mailto:kirk.waters at noaa.gov>>
Sent: Monday, July 8, 2024 7:35 AM
To: Pearson, Scott <pearsonsm at ornl.gov<mailto:pearsonsm at ornl.gov>>
Cc: Paul Harwood <runette at gmail.com<mailto:runette at gmail.com>>; pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
Subject: Re: [pdal] [EXTERNAL] Re: reader.ept error - Could read from

I've seen this error message before with other files. When I pulled the ept.json file to verify, it looked fine. Rerunning the command also worked fine. This has made me believe it's been a network issue. For my automated processes, I now try to catch that response, sleep a minute, and then try again. Has it been consistently failing?

Kirk Waters, PhD
NOAA Office for Coastal Management
Applied Sciences Program
coast.noaa.gov/digitalcoast<https://urldefense.us/v2/url?u=http-3A__coast.noaa.gov_digitalcoast&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=py4GkxTULW8v1KQXRdcuOrApgAtGP2DNvXXiG6LFkWU&e=>




On Mon, Jul 8, 2024 at 7:26?AM Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:
Hi Paul,

The URL is quoted in my input JSON file.  In the email message, Microsoft Outlook converted the URL text to a link and dropped the quotes.  Here?s a snippet from the JSON with quotation marks preserved:
{
    "tag": "ept_reader",
    "type": "readers.ept",
    "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
    "filename": ?https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=2fzUXpUwgQYrH-rkW6_bGLG3pgVPaUTGCCioQXewQRU&e=>?,
    "resolution": "0.01",
    "threads": "4"
  }

Thanks,
Scott


From: Paul Harwood <runette at gmail.com<mailto:runette at gmail.com>>
Sent: Saturday, July 6, 2024 5:10 AM
To: Pearson, Scott <pearsonsm at ornl.gov<mailto:pearsonsm at ornl.gov>>
Cc: pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
Subject: [EXTERNAL] Re: [pdal] reader.ept error - Could read from

I don't know if this is just an artefact of the email - but :

https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>

should be:

"https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>"

On Fri, 5 Jul 2024 at 17:24, Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:
Dear PDAL folks,
 I have an error using readers.ept in a PDAL pipeline.  Using instructions on the Quickstart page<https://urldefense.us/v2/url?u=https-3A__pdal.io_en_2.7.2_quickstart.html&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=su9lNnhWcUnIS-p1ASVmGNvlVbDN_kimfMgeqAjZdLE&e=>, PDAL (v. 2.7.2) is installed using miniconda (conda v. 24.5.0) and applied updates were applied to conda and pdal installations.  The ?pdal info autzen.laz -p 0? command works, so I?ve assume that the PDAL install was successful.
 When I run ?pdal pipeline Plot_176612216020004.json ?debug?, I receive this output and error:
?(PDAL Debug) Debugging...
(pdal pipeline readers.ept Debug) PDAL: readers.ept: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=http-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=grZ4fqpuKLbRQaHxZRQsSUZEWar0gYK3B0ovPUvWjCc&e=> ?
 The contents of Plot_176612216020004.json are:
[
  {
    "tag": "ept_reader",
    "type": "readers.ept",
    "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
    "filename": ?https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=2fzUXpUwgQYrH-rkW6_bGLG3pgVPaUTGCCioQXewQRU&e=>?,
    "resolution": "0.01",
    "threads": "4"
  },
  {
    "tag": "las_writer",
    "type": "writers.las",
    "filename": "USGS_LPC_TN_27County_blk4_2015_LAS_2018_176612216020004.laz",
    "compression": "laszip",
    "extra_dims": "all",
    "forward": "header, vlr",
    "offset_x": "auto",
    "offset_y": "auto",
    "offset_z": "auto",
    "scale_x": "0.01",
    "scale_y": "0.01",
    "scale_z": "0.01"
  }
]

I can access the etp.json file listed under filename using my browser and also using a curl command from the conda prompt.
I have also tried the Iowa example from this tutorial and receive the same ?Could not read from ?.? error.
 Any suggestions for solving this problem?  My overall goal is to download lidar point clouds for a set of 200 field plots (3 ha each).
 Thank you,
Scott
_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=PST3C28-L5iw9E-wtUJA0LshiHNBg78HGTpOn1OH4aU&e=>
_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=EsfMSNspm-xBh9dAu7TmVnuGSiMpcPqQkW6N1vKcGsc&e=>
_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwQFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=NZShMMfOuJLHoVeR7aB7hrcmvywgrppC_teCbyKze5ubAwUlnvaCqttmDCBeE1YK&s=hgUgsHFzkUKKI49JHAS1pCUA-Dwiwa87WVP2JSGfejE&e=>

-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240708/b99c2677/attachment-0001.htm>

From michael.smith.erdc at gmail.com  Mon Jul  8 05:48:58 2024
From: michael.smith.erdc at gmail.com (michael.smith.erdc at gmail.com)
Date: Mon, 8 Jul 2024 15:48:58 +0300
Subject: [pdal] [EXTERNAL] Re: reader.ept error - Could read from
In-Reply-To: <SA9PR09MB5886EEAD2E369D9DDD499C33DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
References: <SA9PR09MB5886EEAD2E369D9DDD499C33DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
Message-ID: <62711942-2B69-46F3-8471-29F31DF7D8B6@gmail.com>

An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240708/6e5fdd1d/attachment-0001.htm>

From pearsonsm at ornl.gov  Mon Jul  8 07:00:54 2024
From: pearsonsm at ornl.gov (Pearson, Scott)
Date: Mon, 8 Jul 2024 14:00:54 +0000
Subject: [pdal] [EXTERNAL] Re: reader.ept error - Could read from
In-Reply-To: <62711942-2B69-46F3-8471-29F31DF7D8B6@gmail.com>
References: <SA9PR09MB5886EEAD2E369D9DDD499C33DFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>
 <62711942-2B69-46F3-8471-29F31DF7D8B6@gmail.com>
Message-ID: <SA9PR09MB5886EF1EA54134790176ABBCDFDA2@SA9PR09MB5886.namprd09.prod.outlook.com>

Hi Michael,

I believe you are correct.  When I switched to a computer not connected to my company?s VPN, the PDAL pipeline executed successfully.

Also, thank you to Howard, Kirk, and Paul for responding to my post. I consider this  problem solved.

Scott

From: michael.smith.erdc at gmail.com <michael.smith.erdc at gmail.com>
Sent: Monday, July 8, 2024 8:49 AM
To: Pearson, Scott <pearsonsm at ornl.gov>
Cc: Howard Butler <howard at hobu.co>; pdal at lists.osgeo.org
Subject: Re: [pdal] [EXTERNAL] Re: reader.ept error - Could read from

This is not uncommon on some corporate networks, they are doing MITM checks and blocking the certificate checks. You might need to see if they have a specific certificate that you should now be using. There is some openssl option to disable the http.schannelCheckRevoke false. You might need to do something curl calls against the s3 url and see what the certificate is that is being used and see if its no longer signed by amazon but by your companies certificate.


Michael Smith
US Army Corps



On Jul 8, 2024, at 3:36?PM, Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:
?
Hi Howard,
Here?s what I see after setting  VERBOSE=1 :


pdal pipeline Plot_176612216020004.json --debug
(PDAL Debug) Debugging...
(pdal pipeline readers.ept Debug) Curl config:
        timeout: 5s
        followRedirect: true
        verifyPeer: true
        caBundle: (default)
        caInfo: (default)
        Proxy: (default)
* Host s3-us-west-2.amazonaws.com:443 was resolved.
* IPv6: (none)
* IPv4: 52.92.147.120, 52.92.128.104, 52.218.236.96, 52.92.152.216, 52.218.183.0, 52.218.237.32, 52.92.180.72, 52.92.138.0
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
* Hostname s3-us-west-2.amazonaws.com was found in DNS cache
*   Trying 52.92.147.120:443...
* Connected to s3-us-west-2.amazonaws.com (52.92.147.120) port 443
* schannel: disabled automatic use of client certificate
* ALPN: curl offers http/1.1
* schannel: next InitializeSecurityContext failed: CRYPT_E_NO_REVOCATION_CHECK (0x80092012) - The revocation function was unable to check revocation for the certificate.
* Closing connection
* schannel: shutting down SSL/TLS connection with s3-us-west-2.amazonaws.com port 443
Curl failure: SSL connect error
PDAL: readers.ept: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json

Thanks,
Scott



From: Howard Butler <howard at hobu.co<mailto:howard at hobu.co>>
Sent: Monday, July 8, 2024 8:25 AM
To: Pearson, Scott <pearsonsm at ornl.gov<mailto:pearsonsm at ornl.gov>>
Cc: Kirk Waters - NOAA Federal <kirk.waters at noaa.gov<mailto:kirk.waters at noaa.gov>>; pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
Subject: Re: [pdal] [EXTERNAL] Re: reader.ept error - Could read from

set VERBOSE=1 in your environment before running your pipeline and include the --debug switch in your pdal command to see if it will emit more diagnostic for you.



On Jul 8, 2024, at 7:05?AM, Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:

Hi Kirk,

I have seen the problem consistently since July 1 and again this morning.  I use a PC that is on my employer?s VPN, which might be contributing to the issue.

Scott

From: Kirk Waters - NOAA Federal <kirk.waters at noaa.gov<mailto:kirk.waters at noaa.gov>>
Sent: Monday, July 8, 2024 7:35 AM
To: Pearson, Scott <pearsonsm at ornl.gov<mailto:pearsonsm at ornl.gov>>
Cc: Paul Harwood <runette at gmail.com<mailto:runette at gmail.com>>; pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
Subject: Re: [pdal] [EXTERNAL] Re: reader.ept error - Could read from

I've seen this error message before with other files. When I pulled the ept.json file to verify, it looked fine. Rerunning the command also worked fine. This has made me believe it's been a network issue. For my automated processes, I now try to catch that response, sleep a minute, and then try again. Has it been consistently failing?

Kirk Waters, PhD
NOAA Office for Coastal Management
Applied Sciences Program
coast.noaa.gov/digitalcoast<https://urldefense.us/v2/url?u=http-3A__coast.noaa.gov_digitalcoast&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=py4GkxTULW8v1KQXRdcuOrApgAtGP2DNvXXiG6LFkWU&e=>




On Mon, Jul 8, 2024 at 7:26?AM Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:
Hi Paul,

The URL is quoted in my input JSON file.  In the email message, Microsoft Outlook converted the URL text to a link and dropped the quotes.  Here?s a snippet from the JSON with quotation marks preserved:
{
    "tag": "ept_reader",
    "type": "readers.ept",
    "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
    "filename": ?https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=2fzUXpUwgQYrH-rkW6_bGLG3pgVPaUTGCCioQXewQRU&e=>?,
    "resolution": "0.01",
    "threads": "4"
  }

Thanks,
Scott


From: Paul Harwood <runette at gmail.com<mailto:runette at gmail.com>>
Sent: Saturday, July 6, 2024 5:10 AM
To: Pearson, Scott <pearsonsm at ornl.gov<mailto:pearsonsm at ornl.gov>>
Cc: pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
Subject: [EXTERNAL] Re: [pdal] reader.ept error - Could read from

I don't know if this is just an artefact of the email - but :

https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>

should be:

"https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=DppyiaHKZxe-lcRF1sMm-tzX3QvrM6XUlmHN-QZEGYo&e=>"

On Fri, 5 Jul 2024 at 17:24, Pearson, Scott via pdal <pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>> wrote:
Dear PDAL folks,
 I have an error using readers.ept in a PDAL pipeline.  Using instructions on the Quickstart page<https://urldefense.us/v2/url?u=https-3A__pdal.io_en_2.7.2_quickstart.html&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=su9lNnhWcUnIS-p1ASVmGNvlVbDN_kimfMgeqAjZdLE&e=>, PDAL (v. 2.7.2) is installed using miniconda (conda v. 24.5.0) and applied updates were applied to conda and pdal installations.  The ?pdal info autzen.laz -p 0? command works, so I?ve assume that the PDAL install was successful.
 When I run ?pdal pipeline Plot_176612216020004.json ?debug?, I receive this output and error:
?(PDAL Debug) Debugging...
(pdal pipeline readers.ept Debug) PDAL: readers.ept: Could not read from s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=http-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=grZ4fqpuKLbRQaHxZRQsSUZEWar0gYK3B0ovPUvWjCc&e=> ?
 The contents of Plot_176612216020004.json are:
[
  {
    "tag": "ept_reader",
    "type": "readers.ept",
    "bounds": "([ -9423306.45485711 , -9421847.59871605 ],[ 4175665.92739632 , 4177131.3660114 ])",
    "filename": ?https://s3-us-west-2.amazonaws.com/usgs-lidar-public/USGS_LPC_TN_27County_blk4_2015_LAS_2018/ept.json<https://urldefense.us/v2/url?u=https-3A__s3-2Dus-2Dwest-2D2.amazonaws.com_usgs-2Dlidar-2Dpublic_USGS-5FLPC-5FTN-5F27County-5Fblk4-5F2015-5FLAS-5F2018_ept.json&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=2fzUXpUwgQYrH-rkW6_bGLG3pgVPaUTGCCioQXewQRU&e=>?,
    "resolution": "0.01",
    "threads": "4"
  },
  {
    "tag": "las_writer",
    "type": "writers.las",
    "filename": "USGS_LPC_TN_27County_blk4_2015_LAS_2018_176612216020004.laz",
    "compression": "laszip",
    "extra_dims": "all",
    "forward": "header, vlr",
    "offset_x": "auto",
    "offset_y": "auto",
    "offset_z": "auto",
    "scale_x": "0.01",
    "scale_y": "0.01",
    "scale_z": "0.01"
  }
]

I can access the etp.json file listed under filename using my browser and also using a curl command from the conda prompt.
I have also tried the Iowa example from this tutorial and receive the same ?Could not read from ?.? error.
 Any suggestions for solving this problem?  My overall goal is to download lidar point clouds for a set of 200 field plots (3 ha each).
 Thank you,
Scott
_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=OdmAeyhN4J3b_xFt4WhzHNuQCyNq824pbGFV3UroI6V5tWNz16wjdyIBWpc7MUa1&s=PST3C28-L5iw9E-wtUJA0LshiHNBg78HGTpOn1OH4aU&e=>
_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwMFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=_j6WrNWoVwy77DWC5EJvBc9LKUL5lV6AlicsKukZeWnLAijORUp4Y6Y6O2QTeSFs&s=EsfMSNspm-xBh9dAu7TmVnuGSiMpcPqQkW6N1vKcGsc&e=>
_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwQFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=NZShMMfOuJLHoVeR7aB7hrcmvywgrppC_teCbyKze5ubAwUlnvaCqttmDCBeE1YK&s=hgUgsHFzkUKKI49JHAS1pCUA-Dwiwa87WVP2JSGfejE&e=>

_______________________________________________
pdal mailing list
pdal at lists.osgeo.org<mailto:pdal at lists.osgeo.org>
https://lists.osgeo.org/mailman/listinfo/pdal<https://urldefense.us/v2/url?u=https-3A__lists.osgeo.org_mailman_listinfo_pdal&d=DwQFaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=HORY163nBbFgyWK0c3Xwo0vnkU1QghnN6V30DBX36lU&m=x3LGGYV3kc3Ol0jeI0lYu6yhQGZMORvNmn7M8Errrov4DnHo5_jGNPO8-yG-8QYJ&s=o-A2w3mMYtX3wAzTIV7i3L9ndLyq1Tb_aNg1uUN3Lzg&e=>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240708/7c337d5c/attachment-0001.htm>

From sionwill at googlemail.com  Mon Jul  8 08:17:50 2024
From: sionwill at googlemail.com (Sion Williams)
Date: Mon, 8 Jul 2024 16:17:50 +0100
Subject: [pdal] What attributes would you add to your pointcloud
Message-ID: <CAJW_ZYVN2SrYqGL6TVK9=EiEwPVmJkxk+Mb3kdQ++mK3aSm6AA@mail.gmail.com>

I am in the process of creating a whole country EPT Entwine pointfile.

I wondering what attributes would the developers/readers add to their
pointfile to use for filtering.

I was thinking:
  normalising the 'intensity' values as so i can compare different dataset
from different light days (investigating identifying with intensity
identifying drystone walls, conifers trees),
 Aspect, slope, local relief, Height Above Ground for features.


On another note: where do we heap praise on the developers. I had no
knowledge of how to do anything with point lidar until I had a major
question at work on finding hedgerows under trees.

And following on from that i have nearly finished doing a whole
country pointcloud in Entwine.

All this was possible thanks to your simplicity in your PDAL software and
ChaptGPT.

Many thanks
Sion
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240708/06f0d163/attachment.htm>

From howard at hobu.co  Tue Jul  9 07:21:04 2024
From: howard at hobu.co (Howard Butler)
Date: Tue, 9 Jul 2024 09:21:04 -0500
Subject: [pdal] What attributes would you add to your pointcloud
In-Reply-To: <CAJW_ZYVN2SrYqGL6TVK9=EiEwPVmJkxk+Mb3kdQ++mK3aSm6AA@mail.gmail.com>
References: <CAJW_ZYVN2SrYqGL6TVK9=EiEwPVmJkxk+Mb3kdQ++mK3aSm6AA@mail.gmail.com>
Message-ID: <8F4493F3-ED24-4152-A646-D66478C7DE5F@hobu.co>



> On Jul 8, 2024, at 10:17?AM, Sion Williams via pdal <pdal at lists.osgeo.org> wrote:
> 
> I am in the process of creating a whole country EPT Entwine pointfile.
> 
> I wondering what attributes would the developers/readers add to their pointfile to use for filtering.
> 
> I was thinking:
>   normalising the 'intensity' values as so i can compare different dataset from different light days (investigating identifying with intensity identifying drystone walls, conifers trees),
>  Aspect, slope, local relief, Height Above Ground for features.

All of these are useful. There is a cost to keeping them all around, however.

> On another note: where do we heap praise on the developers. I had no knowledge of how to do anything with point lidar until I had a major question at work on finding hedgerows under trees. 

Sounds like a fun project.

> And following on from that i have nearly finished doing a whole country pointcloud in Entwine.

Which country?

> All this was possible thanks to your simplicity in your PDAL software and ChaptGPT.

We take pride in people being able to have success with PDAL without intervention by the developers. This is the definition of success for an open source project as far as I'm concerned.

Howard

From sionwill at googlemail.com  Tue Jul  9 08:33:03 2024
From: sionwill at googlemail.com (Sion Williams)
Date: Tue, 9 Jul 2024 16:33:03 +0100
Subject: [pdal] What attributes would you add to your pointcloud
In-Reply-To: <8F4493F3-ED24-4152-A646-D66478C7DE5F@hobu.co>
References: <CAJW_ZYVN2SrYqGL6TVK9=EiEwPVmJkxk+Mb3kdQ++mK3aSm6AA@mail.gmail.com>
 <8F4493F3-ED24-4152-A646-D66478C7DE5F@hobu.co>
Message-ID: <CAJW_ZYVvNz4sZnL2eHTas5GERRdUgRGpuvEnf7VMTt2rjHNSEQ@mail.gmail.com>

One of the uk devolved ones ? .Going to blow peoples minds when they see
the full Entwine dataset. Processing everything easily on a single i7
laptop with 64gb of ram...did not think it would be possible in Opensource.
When the dust settles probably 4months time would love to do a show and
tell document...and can be less cryptic on the country.

Howard I learnt a lot from your youtube video with "ESIP CCC:cloud
optimised point cloud with Howard Butler" ...i reccomend people check it
out...esp for the links of viewer.copc.io & validate.copc.io

Cheers
Sion

On Tue, 9 Jul 2024, 15:21 Howard Butler, <howard at hobu.co> wrote:

>
>
> > On Jul 8, 2024, at 10:17?AM, Sion Williams via pdal <
> pdal at lists.osgeo.org> wrote:
> >
> > I am in the process of creating a whole country EPT Entwine pointfile.
> >
> > I wondering what attributes would the developers/readers add to their
> pointfile to use for filtering.
> >
> > I was thinking:
> >   normalising the 'intensity' values as so i can compare different
> dataset from different light days (investigating identifying with intensity
> identifying drystone walls, conifers trees),
> >  Aspect, slope, local relief, Height Above Ground for features.
>
> All of these are useful. There is a cost to keeping them all around,
> however.
>
> > On another note: where do we heap praise on the developers. I had no
> knowledge of how to do anything with point lidar until I had a major
> question at work on finding hedgerows under trees.
>
> Sounds like a fun project.
>
> > And following on from that i have nearly finished doing a whole country
> pointcloud in Entwine.
>
> Which country?
>
> > All this was possible thanks to your simplicity in your PDAL software
> and ChaptGPT.
>
> We take pride in people being able to have success with PDAL without
> intervention by the developers. This is the definition of success for an
> open source project as far as I'm concerned.
>
> Howard
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240709/244beb5b/attachment.htm>

From dom.jaskierniak at environment.nsw.gov.au  Tue Jul 23 03:03:36 2024
From: dom.jaskierniak at environment.nsw.gov.au (Dom Jaskierniak)
Date: Tue, 23 Jul 2024 10:03:36 +0000
Subject: [pdal] filters.hag_dem not generating HeightAboveGround output
Message-ID: <MEYPR01MB7640BCD29349AA45BA7CA91289A92@MEYPR01MB7640.ausprd01.prod.outlook.com>


Hi,

I tried to generate HeightAboveGround values (using filters.hag_dem) and had no success with below code. The code successfully crops the las file but the output's metadata suggests there is no HeightAboveGround value. I tried to output the las files attributes in a text output to investigate and this also provides no extra dimension "HeightAboveGround". Any help would be appreciated.


# Generate the pipelines_SubGrid for each grid cell
    pipelines_SubGrid = []

    for x in range(min_x, max_x, grid_size):
        for y in range(min_y, max_y, grid_size):
            output_file = f"{output_dir}/tile_{x}_{y}.las"

            pipeline_grid_las = {
                "pipeline": [
                    {
                        "type": "readers.las",
                        "filename": input_file,
                        "spatialreference": "EPSG:4326"
                    },
                    {
                        "type": "filters.crop",
                        "bounds": f"([{x},{x + grid_size}], [{y},{y + grid_size}])"
                    },
                    {
                        "type":"filters.hag_dem",
                        "raster": dem_file
                    },
                    {
                        "type": "writers.las",
                        "filename": output_file,
                        "extra_dims":"HeightAboveGround=float32"
                    }
                ]
            }
            pipelines_SubGrid.append(pipeline_grid_las)


            ##########################
            pdal_pipeline = pdal.Pipeline(json.dumps(pipeline_grid_las))
            pdal_pipeline.execute()

Thanks in advance!


Regards,
Dom

----------------------------------------------------------------------------------------------------------------------------------------------------------------------
This email is intended for the addressee(s) named and may contain confidential and/or privileged information. 
If you are not the intended recipient, please notify the sender and then delete it immediately.
Any views expressed in this email are those of the individual sender except where the sender expressly and with authority states them to be the views of the NSW Office of Environment and Heritage.

PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240723/e4542bd1/attachment-0001.htm>

From nickholshouser at gmail.com  Tue Jul 23 04:40:27 2024
From: nickholshouser at gmail.com (Nick Holshouser)
Date: Tue, 23 Jul 2024 07:40:27 -0400
Subject: [pdal] filters.hag_dem not generating HeightAboveGround
In-Reply-To: <mailman.210462.1721729024.32175.pdal@lists.osgeo.org>
References: <mailman.210462.1721729024.32175.pdal@lists.osgeo.org>
Message-ID: <CANurM1QPWjDyvu_SGYinFUMSWdkK4pzMNP+zRjc2OgQyJAEzMg@mail.gmail.com>

>
>
> Hello Dom,
>

I had the same problem when writing the HeightAboveGround as extra_dims and
got the hint to use minor_version:4 - which resolved the issue. The data
was there but couldn't be read/displayed by pdal info.

Rerunning the pipeline using minor_version got the result I wanted.

    {

      "extra_dims": "HeightAboveGround=double",

      "filename": "GRID_2789/GRID_2789_HAGDIM_EPSG3857.laz",

      "inputs":

      [

        "writers_las1"

      ],

      "minor_version": "4",

      "pdal_metadata": "true",

      "tag": "writers_las2",

      "type": "writers.las"

    }

Then -p gets:

"points":

  {

    "point":

    {

      "Blue": 0,

      "Classification": 2,

      "EdgeOfFlightLine": 0,

      "GpsTime": 172651632,

      "Green": 94,

      "HeightAboveGround": 0,

      "Intensity": 18668,

      "NumberOfReturns": 1,

      "PointId": 54787,

      "PointSourceId": 0,

      "Red": 198,

      "ReturnNumber": 1,

      "ScanAngleRank": 15,

      "ScanDirectionFlag": 0,

      "UserData": 0,

      "X": -9169790.9,

      "Y": 4268594.4,

      "Z": 890.52
    }

I had missed this in the docs: https://pdal.io/en/latest/tutorial/las.html
(look for minor_version and extra_dims)


> regards, Nick
>



> ----------------------------------------------------------------------
>
> Message: 1
> Date: Tue, 23 Jul 2024 10:03:36 +0000
> From: Dom Jaskierniak <dom.jaskierniak at environment.nsw.gov.au>
> To: "pdal at lists.osgeo.org" <pdal at lists.osgeo.org>
> Subject: [pdal] filters.hag_dem not generating HeightAboveGround
>         output
> Message-ID:
>         <
> MEYPR01MB7640BCD29349AA45BA7CA91289A92 at MEYPR01MB7640.ausprd01.prod.outlook.com
> >
>
> Content-Type: text/plain; charset="us-ascii"
>
>
> Hi,
>
> I tried to generate HeightAboveGround values (using filters.hag_dem) and
> had no success with below code. The code successfully crops the las file
> but the output's metadata suggests there is no HeightAboveGround value. I
> tried to output the las files attributes in a text output to investigate
> and this also provides no extra dimension "HeightAboveGround". Any help
> would be appreciated.
>
>
> # Generate the pipelines_SubGrid for each grid cell
>     pipelines_SubGrid = []
>
>     for x in range(min_x, max_x, grid_size):
>         for y in range(min_y, max_y, grid_size):
>             output_file = f"{output_dir}/tile_{x}_{y}.las"
>
>             pipeline_grid_las = {
>                 "pipeline": [
>                     {
>                         "type": "readers.las",
>                         "filename": input_file,
>                         "spatialreference": "EPSG:4326"
>                     },
>                     {
>                         "type": "filters.crop",
>                         "bounds": f"([{x},{x + grid_size}], [{y},{y +
> grid_size}])"
>                     },
>                     {
>                         "type":"filters.hag_dem",
>                         "raster": dem_file
>                     },
>                     {
>                         "type": "writers.las",
>                         "filename": output_file,
>                         "extra_dims":"HeightAboveGround=float32"
>                     }
>                 ]
>             }
>             pipelines_SubGrid.append(pipeline_grid_las)
>
>
>             ##########################
>             pdal_pipeline = pdal.Pipeline(json.dumps(pipeline_grid_las))
>             pdal_pipeline.execute()
>
> Thanks in advance!
>
>
> Regards,
> Dom
>
>
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
> This email is intended for the addressee(s) named and may contain
> confidential and/or privileged information.
> If you are not the intended recipient, please notify the sender and then
> delete it immediately.
> Any views expressed in this email are those of the individual sender
> except where the sender expressly and with authority states them to be the
> views of the NSW Office of Environment and Heritage.
>
> PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL
> -------------- next part --------------
> An HTML attachment was scrubbed...
> URL: <
> http://lists.osgeo.org/pipermail/pdal/attachments/20240723/e4542bd1/attachment.htm
> >
>
> ------------------------------
>
> Subject: Digest Footer
>
> _______________________________________________
> pdal mailing list
> pdal at lists.osgeo.org
> https://lists.osgeo.org/mailman/listinfo/pdal
>
>
> ------------------------------
>
> End of pdal Digest, Vol 151, Issue 11
> *************************************
>
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240723/c9df8ac1/attachment.htm>

From dom.jaskierniak at environment.nsw.gov.au  Tue Jul 23 22:36:05 2024
From: dom.jaskierniak at environment.nsw.gov.au (Dom Jaskierniak)
Date: Wed, 24 Jul 2024 05:36:05 +0000
Subject: [pdal] filters.hag_dem not generating HeightAboveGround output
In-Reply-To: <mailman.210462.1721729024.32175.pdal@lists.osgeo.org>
References: <mailman.210462.1721729024.32175.pdal@lists.osgeo.org>
Message-ID: <MEYPR01MB7640582C0DB5ECCE60774D8289AA2@MEYPR01MB7640.ausprd01.prod.outlook.com>

Hi,

I found that filters.hag_dem was not generating HeightAboveGround output because I was working with a LAS 1.2 format, which does not support extra dimensions.

For it to work, it was necessary to put in "minor_version": 4 in:

                    {
                        "type": "writers.las",
                        "filename": output_file,
	          "minor_version": 4  # Ensure LAS 1.4 format	
                        "extra_dims":"HeightAboveGround=float32"
                    }

It would be helpful for all operations that require extra dimensions to check the LAS format first and throw a warning if it format is not compatible with extra dimensions.

Regards,
Dom



-----Original Message-----
From: pdal <pdal-bounces at lists.osgeo.org> On Behalf Of pdal-request at lists.osgeo.org
Sent: Tuesday, July 23, 2024 8:04 PM
To: pdal at lists.osgeo.org
Subject: pdal Digest, Vol 151, Issue 11

Send pdal mailing list submissions to
	pdal at lists.osgeo.org

To subscribe or unsubscribe via the World Wide Web, visit
	https://lists.osgeo.org/mailman/listinfo/pdal
or, via email, send a message with subject or body 'help' to
	pdal-request at lists.osgeo.org

You can reach the person managing the list at
	pdal-owner at lists.osgeo.org

When replying, please edit your Subject line so it is more specific than "Re: Contents of pdal digest..."


Today's Topics:

   1. filters.hag_dem not generating HeightAboveGround output
      (Dom Jaskierniak)


----------------------------------------------------------------------

Message: 1
Date: Tue, 23 Jul 2024 10:03:36 +0000
From: Dom Jaskierniak <dom.jaskierniak at environment.nsw.gov.au>
To: "pdal at lists.osgeo.org" <pdal at lists.osgeo.org>
Subject: [pdal] filters.hag_dem not generating HeightAboveGround
	output
Message-ID:
	<MEYPR01MB7640BCD29349AA45BA7CA91289A92 at MEYPR01MB7640.ausprd01.prod.outlook.com>
	
Content-Type: text/plain; charset="us-ascii"


Hi,

I tried to generate HeightAboveGround values (using filters.hag_dem) and had no success with below code. The code successfully crops the las file but the output's metadata suggests there is no HeightAboveGround value. I tried to output the las files attributes in a text output to investigate and this also provides no extra dimension "HeightAboveGround". Any help would be appreciated.


# Generate the pipelines_SubGrid for each grid cell
    pipelines_SubGrid = []

    for x in range(min_x, max_x, grid_size):
        for y in range(min_y, max_y, grid_size):
            output_file = f"{output_dir}/tile_{x}_{y}.las"

            pipeline_grid_las = {
                "pipeline": [
                    {
                        "type": "readers.las",
                        "filename": input_file,
                        "spatialreference": "EPSG:4326"
                    },
                    {
                        "type": "filters.crop",
                        "bounds": f"([{x},{x + grid_size}], [{y},{y + grid_size}])"
                    },
                    {
                        "type":"filters.hag_dem",
                        "raster": dem_file
                    },
                    {
                        "type": "writers.las",
                        "filename": output_file,
                        "extra_dims":"HeightAboveGround=float32"
                    }
                ]
            }
            pipelines_SubGrid.append(pipeline_grid_las)


            ##########################
            pdal_pipeline = pdal.Pipeline(json.dumps(pipeline_grid_las))
            pdal_pipeline.execute()

Thanks in advance!


Regards,
Dom

----------------------------------------------------------------------------------------------------------------------------------------------------------------------
This email is intended for the addressee(s) named and may contain confidential and/or privileged information. 
If you are not the intended recipient, please notify the sender and then delete it immediately.
Any views expressed in this email are those of the individual sender except where the sender expressly and with authority states them to be the views of the NSW Office of Environment and Heritage.

PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240723/e4542bd1/attachment.htm>

------------------------------

Subject: Digest Footer

_______________________________________________
pdal mailing list
pdal at lists.osgeo.org
https://lists.osgeo.org/mailman/listinfo/pdal


------------------------------

End of pdal Digest, Vol 151, Issue 11
*************************************
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
This email is intended for the addressee(s) named and may contain confidential and/or privileged information. 
If you are not the intended recipient, please notify the sender and then delete it immediately.
Any views expressed in this email are those of the individual sender except where the sender expressly and with authority states them to be the views of the NSW Office of Environment and Heritage.

PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL


From andrew.bell.ia at gmail.com  Wed Jul 24 06:22:25 2024
From: andrew.bell.ia at gmail.com (Andrew Bell)
Date: Wed, 24 Jul 2024 09:22:25 -0400
Subject: [pdal] filters.hag_dem not generating HeightAboveGround output
In-Reply-To: <MEYPR01MB7640582C0DB5ECCE60774D8289AA2@MEYPR01MB7640.ausprd01.prod.outlook.com>
References: <mailman.210462.1721729024.32175.pdal@lists.osgeo.org>
 <MEYPR01MB7640582C0DB5ECCE60774D8289AA2@MEYPR01MB7640.ausprd01.prod.outlook.com>
Message-ID: <CACJ51z1Xni0w_M_mgR7EXz-0qUsfE6XVRB1L8nPMM3LOR-8wOQ@mail.gmail.com>

There is nothing that wasn't working as far as I can tell. You wrote a
version 1.2 file with an extra dimension "HeightAboveGround". This is
allowed by the 1.2 specification. PDAL writes an "extra_dims" VLR if there
are extra dimensions written to the file. It does this for all minor
versions, even though the VLR wasn't defined until version 1.4. PDAL will
read this VLR on a 1.2 file if you tell it to (see the "use_eb_vlr"
option), but you can also explicitly tell PDAL what data is tacked on to
the end of a standard point record with the "extra_dims" option.

The LAS specification isn't too long and is worth a read if you are going
to store data in the LAS format.

On Wed, Jul 24, 2024 at 1:36?AM Dom Jaskierniak via pdal <
pdal at lists.osgeo.org> wrote:

> Hi,
>
> I found that filters.hag_dem was not generating HeightAboveGround output
> because I was working with a LAS 1.2 format, which does not support extra
> dimensions.
>
> For it to work, it was necessary to put in "minor_version": 4 in:
>
>                     {
>                         "type": "writers.las",
>                         "filename": output_file,
>                   "minor_version": 4  # Ensure LAS 1.4 format
>                         "extra_dims":"HeightAboveGround=float32"
>                     }
>
> It would be helpful for all operations that require extra dimensions to
> check the LAS format first and throw a warning if it format is not
> compatible with extra dimensions.
>
> Regards,
> Dom
>
>
>
> -----Original Message-----
> From: pdal <pdal-bounces at lists.osgeo.org> On Behalf Of
> pdal-request at lists.osgeo.org
> Sent: Tuesday, July 23, 2024 8:04 PM
> To: pdal at lists.osgeo.org
> Subject: pdal Digest, Vol 151, Issue 11
>
> Send pdal mailing list submissions to
>         pdal at lists.osgeo.org
>
> To subscribe or unsubscribe via the World Wide Web, visit
>         https://lists.osgeo.org/mailman/listinfo/pdal
> or, via email, send a message with subject or body 'help' to
>         pdal-request at lists.osgeo.org
>
> You can reach the person managing the list at
>         pdal-owner at lists.osgeo.org
>
> When replying, please edit your Subject line so it is more specific than
> "Re: Contents of pdal digest..."
>
>
> Today's Topics:
>
>    1. filters.hag_dem not generating HeightAboveGround output
>       (Dom Jaskierniak)
>
>
> ----------------------------------------------------------------------
>
> Message: 1
> Date: Tue, 23 Jul 2024 10:03:36 +0000
> From: Dom Jaskierniak <dom.jaskierniak at environment.nsw.gov.au>
> To: "pdal at lists.osgeo.org" <pdal at lists.osgeo.org>
> Subject: [pdal] filters.hag_dem not generating HeightAboveGround
>         output
> Message-ID:
>         <
> MEYPR01MB7640BCD29349AA45BA7CA91289A92 at MEYPR01MB7640.ausprd01.prod.outlook.com
> >
>
> Content-Type: text/plain; charset="us-ascii"
>
>
> Hi,
>
> I tried to generate HeightAboveGround values (using filters.hag_dem) and
> had no success with below code. The code successfully crops the las file
> but the output's metadata suggests there is no HeightAboveGround value. I
> tried to output the las files attributes in a text output to investigate
> and this also provides no extra dimension "HeightAboveGround". Any help
> would be appreciated.
>
>
> # Generate the pipelines_SubGrid for each grid cell
>     pipelines_SubGrid = []
>
>     for x in range(min_x, max_x, grid_size):
>         for y in range(min_y, max_y, grid_size):
>             output_file = f"{output_dir}/tile_{x}_{y}.las"
>
>             pipeline_grid_las = {
>                 "pipeline": [
>                     {
>                         "type": "readers.las",
>                         "filename": input_file,
>                         "spatialreference": "EPSG:4326"
>                     },
>                     {
>                         "type": "filters.crop",
>                         "bounds": f"([{x},{x + grid_size}], [{y},{y +
> grid_size}])"
>                     },
>                     {
>                         "type":"filters.hag_dem",
>                         "raster": dem_file
>                     },
>                     {
>                         "type": "writers.las",
>                         "filename": output_file,
>                         "extra_dims":"HeightAboveGround=float32"
>                     }
>                 ]
>             }
>             pipelines_SubGrid.append(pipeline_grid_las)
>
>
>             ##########################
>             pdal_pipeline = pdal.Pipeline(json.dumps(pipeline_grid_las))
>             pdal_pipeline.execute()
>
> Thanks in advance!
>
>
> Regards,
> Dom
>
>
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
> This email is intended for the addressee(s) named and may contain
> confidential and/or privileged information.
> If you are not the intended recipient, please notify the sender and then
> delete it immediately.
> Any views expressed in this email are those of the individual sender
> except where the sender expressly and with authority states them to be the
> views of the NSW Office of Environment and Heritage.
>
> PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL
> -------------- next part --------------
> An HTML attachment was scrubbed...
> URL: <
> http://lists.osgeo.org/pipermail/pdal/attachments/20240723/e4542bd1/attachment.htm
> >
>
> ------------------------------
>
> Subject: Digest Footer
>
> _______________________________________________
> pdal mailing list
> pdal at lists.osgeo.org
> https://lists.osgeo.org/mailman/listinfo/pdal
>
>
> ------------------------------
>
> End of pdal Digest, Vol 151, Issue 11
> *************************************
>
> ----------------------------------------------------------------------------------------------------------------------------------------------------------------------
> This email is intended for the addressee(s) named and may contain
> confidential and/or privileged information.
> If you are not the intended recipient, please notify the sender and then
> delete it immediately.
> Any views expressed in this email are those of the individual sender
> except where the sender expressly and with authority states them to be the
> views of the NSW Office of Environment and Heritage.
>
> PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL
>
> _______________________________________________
> pdal mailing list
> pdal at lists.osgeo.org
> https://lists.osgeo.org/mailman/listinfo/pdal
>


-- 
Andrew Bell
andrew.bell.ia at gmail.com
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240724/a664bdaf/attachment-0001.htm>

From dom.jaskierniak at environment.nsw.gov.au  Tue Jul 30 23:47:03 2024
From: dom.jaskierniak at environment.nsw.gov.au (Dom Jaskierniak)
Date: Wed, 31 Jul 2024 06:47:03 +0000
Subject: [pdal] waveform pdal plugins
Message-ID: <MEYPR01MB76404E74786EB3C3B9240E0189B12@MEYPR01MB7640.ausprd01.prod.outlook.com>

Hi,

I am aware that pdal doesn't support point formats that store waveform data (see LAS Versions in https://pdal.io/en/2.7.2/tutorial/las.html#id4
). Are there pdal plugins that allow for waveform data integration into pdal pipelines?

Alternatively, can the community recommend an alternative ( i.e. most reliable waveform lidar package for python code)?

Thank you!

Dom


Dr Dom Jaskierniak
Senior Scientist (Remote Sensing and Landscape Sciences)

Science, Economics and Insights Division| Department of Climate Change, Energy, the Environment and Water
M 0498 206 030  |  E dom.jaskierniak at environment.nsw.gov.au
Level 3, 6 Stewart Avenue, Newcastle, NSW, 2302

www.dpie.nsw.gov.au<http://www.dpie.nsw.gov.au/>
[cid:image001.png at 01DAE369.2D7737F0]<http://www.dpie.nsw.gov.au/>
The Department of Planning and Environment acknowledges that it stands on Aboriginal land.
We acknowledge the traditional custodians of the land and we show our respect for elders past, present
and emerging through thoughtful and collaborative approaches to our work, seeking to demonstrate our ongoing
commitment to providing places in which Aboriginal people are included socially, culturally and economically.

----------------------------------------------------------------------------------------------------------------------------------------------------------------------
This email is intended for the addressee(s) named and may contain confidential and/or privileged information. 
If you are not the intended recipient, please notify the sender and then delete it immediately.
Any views expressed in this email are those of the individual sender except where the sender expressly and with authority states them to be the views of the NSW Office of Environment and Heritage.

PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS EMAIL
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240731/a32867bb/attachment-0001.htm>
-------------- next part --------------
A non-text attachment was scrubbed...
Name: image001.png
Type: image/png
Size: 117661 bytes
Desc: image001.png
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240731/a32867bb/attachment-0001.png>

From howard at hobu.co  Wed Jul 31 07:16:39 2024
From: howard at hobu.co (Howard Butler)
Date: Wed, 31 Jul 2024 09:16:39 -0500
Subject: [pdal] waveform pdal plugins
In-Reply-To: <MEYPR01MB76404E74786EB3C3B9240E0189B12@MEYPR01MB7640.ausprd01.prod.outlook.com>
References: <MEYPR01MB76404E74786EB3C3B9240E0189B12@MEYPR01MB7640.ausprd01.prod.outlook.com>
Message-ID: <09EBCB9D-C7B2-4879-8C05-ABDE5B53457A@hobu.co>



> On Jul 31, 2024, at 1:47?AM, Dom Jaskierniak via pdal <pdal at lists.osgeo.org> wrote:
> 
> Hi, <>
>  
> I am aware that pdal doesn?t support point formats that store waveform data (see LAS Versions in https://pdal.io/en/2.7.2/tutorial/las.html#id4
> ). Are there pdal plugins that allow for waveform data integration into pdal pipelines?

Nope, no plugins for waveform stuff for PDAL. PDAL is just about points
>  
> Alternatively, can the community recommend an alternative ( i.e. most reliable waveform lidar package for python code)?

Isenburg's PulseWaves is quite useful and might be a place to start, but it isn't python code https://github.com/PulseWaves/PulseWaves

Howard
-------------- next part --------------
An HTML attachment was scrubbed...
URL: <http://lists.osgeo.org/pipermail/pdal/attachments/20240731/b509d296/attachment.htm>

